; This file is automatically generated by the top-level EVEBot.iss

#if ${EVEBotBehaviors.Element[obj_BeltRunner]}
	Logger:Log["Creating global obj_BeltRunner as BeltRunner", LOG_DEBUG]
	call CreateVariable BeltRunner obj_BeltRunner global
#endif

