/*
	defines.iss
	
	Hardcoded defines for EVEBot
	
	- CyberTech
	
*/

#define WAIT_CARGO_WINDOW 15
#define WAIT_UNDOCK 130

#define GROUPID_ASTEROID_BELT 9

#define GROUPID_AFTERBURNER 46
#define GROUPID_SHIELD_BOOSTER 40
#define GROUPID_MINING_CRYSTAL 482
#define GROUPID_FREQUENCY_MINING_LASER 483

#define LOOT_RANGE 1450